---
title: "Mozart409 Dashboard"
subtitle: "Homer"
header: true 
logo: 'assets/images/dark_circle.png'
stylesheet:
  - 'assets/catppuccin-mocha.css'
theme: 'catppuccin-macchiato'
message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  # mapping: # allows to map fields from the remote format to the one expected by Homer
  #   title: 'id' # use value from field 'id' as title
  #   content: 'value' # value from field 'value' as content
  # refreshInterval: 10000 # Optional: time interval to refresh message
  #
  # Real example using chucknorris.io for showing Chuck Norris facts as messages:
  # url: https://api.chucknorris.io/jokes/random
  # mapping:
  #   title: 'id'
  #   content: 'value'
  # refreshInterval: 10000
  # style: "is-warning"
  # title: "Optional message!"
  # icon: "fa fa-exclamation-triangle"
  # content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit."


links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/mozart409"
    target: "_blank" # optional html tag target attribute
  - name: "Coolify"
    icon: "fa fa-server"
    url: "https://coolify.mozart409.host"
    target: "_blank"


services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Tandoor"
        logo: "fas fa-book"
        tag: "food"
        keywords: "self hosted tandoor"
        url: "https://tandoor.mozart409.host"
        target: "_blank"
