title: "Mozart409 Dashboard"
subtitle: "Homer"
header: true
logo: 'assets/images/dark_circle.png'
stylesheet:
  - 'assets/catppuccin-mocha.css'
theme: 'catppuccin-macchiato'
footer: '<img src="/assets/images/footer.png" alt="footer" />'
links:
  - name: "Github"
    icon: "fab fa-github"
    url: "https://github.com/mozart409"
    target: "_blank" # optional html tag target attribute
  - name: "Coolify"
    icon: "fa fa-server"
    url: "https://coolify.mozart409.host"
    target: "_blank"
colors:
  light:
    background-image: "/assets/images/romb.png"
  dark:
    background-image: "/assets/images/romb.png"
services:
  - name: "Applications"
    icon: "fas fa-cloud"
    items:
      - name: "Tandoor"
        logo: "assets/images/tandoor.svg"
        tag: "food"
        keywords: "food"
        url: "https://tandoor.mozart409.host"
        target: "_blank"
      - name: "Cloudflare"
        logo: "https://www.cloudflare.com/favicon.ico"
        tag: "cloud"
        keywords: "cf"
        url: "https://cloudflare.com"
        target: "_blank"
      - name: "Tailscale"
        logo: "https://login.tailscale.com/favicon.ico"
        tag: "cloud"
        keywords: "network"
        url: "https://login.tailscale.com/admin/machines"
        target: "_blank"
      - name: "Pi-Hole"
        logo: "https://rhubarb.dropbear-butterfly.ts.net/admin/img/logo.svg"
        tag: "Network-wide Ad Blocking"
        keywords: ["Pi-Hole", "Ad Blocking", "Network"]
        url: "https://rhubarb.dropbear-butterfly.ts.net/admin/"
      - name: "Homeassistant"
        logo: "https://www.home-assistant.io/images/favicon-192x192.png"
        tag: "Awaken your home"
        keywords: ["Homeassistant", "Home Automation", "Smart Home"]
        url: "https://homeassistant.dropbear-butterfly.ts.net/lovelace/default_view"
  - name: "Productivity"
    icon: "fas fa-mail"
    items:
      - name: "Proton Mail"
        logo: "https://mail.proton.me/assets/favicon.ico"
        tag: "mail"
        keywords: "mail"
        url: "https://mail.protonmail.com/"
        target: "_blank"
      - name: "Proton Calendar"
        logo: "https://calendar.proton.me/assets/favicon.ico"
        url: "https://calendar.proton.me"
  - name: "Projects"
    icon: "fas fa-cloud"
    items:
      - name: "Fly.io"
        logo: "https://fly.io/favicon.ico"
        url: "https://fly.io/dashboard"
