name: ci

on:
  push:
    branches:
      - main

env: 
  REGISTRY: ghcr.io
  IMAGE: ${{ github.repository }}

jobs:
  buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/mozart409/homer:latest .
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/mozart409/homer:${{ github.sha }} .
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/mozart409/homer:latest -t ghcr.io/mozart409/homer:${{ github.sha }} .
          docker push ghcr.io/mozart409/homer:latest
          docker push ghcr.io/mozart409/homer:${{ github.sha }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
